import { existsSync } from "node:fs";
import { basename, extname, join } from "node:path";
import { getAssetPath } from "./withBase";

/**
 * Widths (in px) the cover pipeline generates. Keep in sync with
 * COVER_WIDTHS in scripts/gen-covers.mjs — variants are probed on
 * disk, so a missing file simply drops out of the srcset (dev
 * mode before the pipeline runs falls back to the original file).
 */
export const COVER_VARIANT_WIDTHS = [320, 480, 768, 1280] as const;

/**
 * Card thumbnails render at w-28 (112px) / sm:w-40 (160px), so
 * 2–3× DPR only needs the two smallest variants.
 */
export const COVER_THUMB_WIDTHS = [320, 480] as const;

/**
 * The reading-page cover spans the content column (max 44rem,
 * 67rem in wide mode), which needs the larger variants.
 */
export const COVER_HERO_WIDTHS = [480, 768, 1280] as const;

export type CoverSource = {
  type: "image/avif" | "image/webp";
  srcset: string;
};

export type CoverImageSet = {
  /** Modern-format <source> entries, AVIF first. Empty for remote
   *  covers or before the variant pipeline has run. */
  sources: CoverSource[];
  /** <img> fallback src: the original file for local covers. */
  src: string;
  /** Intrinsic-size hint for the fallback (covers are 16:10). */
  width: number;
  height: number;
};

const PUBLIC_DIR = join(process.cwd(), "public");

/**
 * Resolve a post's `cover` frontmatter value into a <picture>
 * source set. Local covers get WebP/AVIF srcsets from the variants
 * generated by scripts/gen-covers.mjs; absolute URLs pass through
 * untouched (their sizes are unknown to the build). Returns null
 * when no cover is set, so callers can skip rendering the image.
 */
export function getCoverImageSet(
  cover: string | null | undefined,
  widths: readonly number[] = COVER_VARIANT_WIDTHS
): CoverImageSet | null {
  if (!cover) return null;

  if (/^https?:\/\//.test(cover)) {
    return { sources: [], src: cover, width: 640, height: 400 };
  }

  const relativePath = cover.replace(/^\/+/, "");
  const name = basename(relativePath, extname(relativePath));
  const variantDir = join(PUBLIC_DIR, "covers");

  const toSrcset = (extension: string) =>
    widths
      .filter(width =>
        existsSync(join(variantDir, `${name}-${width}w.${extension}`))
      )
      .map(
        width =>
          `${getAssetPath(`covers/${name}-${width}w.${extension}`)} ${width}w`
      )
      .join(", ");

  const sources: CoverSource[] = [];
  const avifSrcset = toSrcset("avif");
  if (avifSrcset) {
    sources.push({ type: "image/avif", srcset: avifSrcset });
  }
  const webpSrcset = toSrcset("webp");
  if (webpSrcset) {
    sources.push({ type: "image/webp", srcset: webpSrcset });
  }

  return {
    sources,
    src: getAssetPath(relativePath),
    width: 640,
    height: 400,
  };
}
